export const ADD_PRODUCT_ITEM="ADD_PRODUCT_ITEM";
export const REMOVE_PRODUCTS_ITEM="REMOVE_PRODUCTS_ITEM";
export const Edit_Value="Edit_Value";
export const ALL_REMOVE_PRODUCTS_ITEM="ALL_REMOVE_PRODUCTS_ITEM";